name: 'Responsiveness Score'
description: 'Measure the responsiveness of PR/issues in the last x months, where x is 1 unless otherwise specified.'
inputs:
    repo-token:
      description: 'Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}.'
      required: true
    repo-name:
        description: 'Name of this repository.'
        required: true
    repo-owner:
        description: 'Owner of this repository.'
        required: true
    moodbar-message:
      description: 'Text for the monthly message to the community. If not provided, the default message will be used.'
      required: false 
    mentors:
        description: 'Comma-separated list of mentors that could potentially follow-up that will be mentioned on the post. Optional.'
        required: false 
    feedback-form:
        description: 'A link to a feedback form. Optional.'
        required: false 
runs:
  using: 'node12'
  main: 'index.js'
